#!/usr/bin/env zsh
source ~/.zshrc

while 1; do

  sleep 1

  deployedVersion=`curl -Lfs http://painkillergis.com.s3.amazonaws.com/version.txt`
  localVersion=`git rev-list --count HEAD`

  if [ "`current_branch`" != "main" ]; then
    continue
  fi

  if ! [[ "$deployedVersion" =~ "^[0-9]+$" ]]; then
    echo deployed version is not a number: $deployedVersion
    continue
  fi

  if [ "$localVersion" -gt "$deployedVersion" ]; then
    echo deploying version $localVersion
    yarn build
    echo $localVersion > build/version.txt
    aws s3 sync build/ s3://painkillergis.com/
    aws cloudfront create-invalidation --distribution-id E2ELSINNBJU4IM --invalidation-batch "Paths={Quantity=1,Items=['/']},CallerReference=`uuidgen`"
    echo deployment successful
  fi

done
